### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by albasili** [nvie/vim-rst-tables#28]
hi,

I apologize but I cannot make it working, I tried the tutorial.rst and the keybindings do not work for me, neither the comma version nor the leader one.

Could anyone help me debug this out?
Cheers,

Al

**Comment by dcrozz** [comment]
@albasili 
I also find the problem when I call ReformatTable(), it shows:
```
Error detected while processing function ReflowTable:
line    7:
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 269, in reflow_table
  File "<string>", line 26, in get_table_bounds
```

I now use [`mgaitan/sublime-rst-completion`](https://github.com/mgaitan/sublime-rst-completion) in sublime text which the original code of this feature was taken from this project to ease my suffering from building table in rst.

**Comment by wdoekes** [comment]
@albasili, perhaps you're using vim+python3?

Please try if https://github.com/ossobv/vim-rst-tables-py3 works for you.

**Comment by curlyclothes104** [comment]
Just to share, tablify works for me and it's more up-to-date https://github.com/Stormherz/tablify
